build-job:
  stage: build
  script:
    - echo "Hello $GITLAB_USER_LOGIN!"
unit_test:
  stage: test
  script:
    - echo "This job tests something"
    - ./gradlew test


test-job2:
  stage: test
  script:
    - echo "Test 2.0 take more time than test1"
    - echo "Test 2.1 take more time than test1"
    - echo "Test 2.2 take more time than test1"
    - sleep 20
deploy-prod:
  stage: deploy
  script :
  - echo "This job deploy from $CI_COMMIT_BRANCH"

environment: production