name: Android CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  ANDROID_ARCH: x86_64
  ANDROID_TARGET: google_apis_playstore
  API_LEVEL: 33
  ANDROID_BUILD_TOOLS_VERSION: 33.0.2
  ANDROID_SDK_PACKAGES: system-images;android-33;google_apis_playstore;x86_64 platforms;android-33 build-tools;33.0.2 platform-tools emulator
  EMULATOR_TIMEOUT: 350
  EMULATOR_NAME: nexus

jobs:
  #job build
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup jdk 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'
      
      - name: Setup android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 34
          build-tools: "34.0.0"
      
      - name: Grant execute permission for Gradle wrapper
        run: chmod +x ./gradlew

      # build SDK

      # - name: Build APK
      #   run: ./gradlew assembleRelease
      # - name: Unit test
      #   run: ./gradlew test
 
  unittest:
   
    timeout-minutes: 20
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3   
      - name: Add avdmanager and sdkmanager to system PATH
        run: |
            echo "$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/emulator:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools:$ANDROID_HOME/build-tools/${{ env.ANDROID_BUILD_TOOLS_VERSION }}" >> $GITHUB_PATH

      - name: Install Sdk
        run: |
           yes Y | sdkmanager --licenses
           sdkmanager --install ${ANDROID_SDK_PACKAGES}
  
      - name: Build emulator
        run: |
            echo "no" | avdmanager --verbose create avd --force -n $EMULATOR_NAME --abi "${ANDROID_TARGET}/${ANDROID_ARCH}" -k "system-images;android-${API_LEVEL};${ANDROID_TARGET};${ANDROID_ARCH}"

      - name: Launch emulator
        run: |
          chmod +x ./start_emu_headless.sh
          EMULATOR_TIMEOUT=$EMULATOR_TIMEOUT EMULATOR_NAME=$EMULATOR_NAME ./start_emu_headless.sh

    steps:
      # run init test
      - name: Checkout code
        uses: actions/checkout@v2
    
      - name: Setup jdk 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'
      
      - name: Setup android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 34
          build-tools: "34.0.0"
        
      - name: Grant execute permission for Gradle wrapper
        run: chmod +x ./gradlew

      - name: Run Unit Tests
        run: ./gradlew test
      
      - name: Run Integration Tests
        run: ./gradlew connectedAndroidTest
  
