name: Android Emulator

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Corrected version

      - name: Set up Java 17
        uses: actions/setup-java@v2  # Use Java 17
        with:
          distribution: 'temurin'
          java-version: '17'  # Update to Java 17
      
      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 30
          build-tools: '30.0.3'

      - name: Start Emulator and Run Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29  # Adjust this API level based on your needs
          target: default
          arch: x86_64
          script: ./gradlew connectedCheck
          disable-animations: true
          emulator-options: -no-window -gpu swiftshader_indirect -no-snapshot
